# Generated by Django 3.2.19 on 2023-10-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4comments', '0013_set_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_reviewed',
        ),
        migrations.AddField(
            model_name='comment',
            name='quality',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='comment',
            name='s',
            field=models.BooleanField(default=False),
        ),
    ]
