# Generated by Django 3.2.19 on 2023-10-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4comments', '0014_auto_20231002_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='s',
            new_name='is_reviewed',
        ),
    ]
